# Generated by Django 5.0.3 on 2024-03-30 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Survey_filled',
        ),
    ]
